### ISSUE TITLE
gradlew.bat fails; gradle generate also

### ISSUE THREAD

**Issue by dheldt** [sysgears/grain-theme-new-age#1]
Hi,

I downloaded and tried to execute gradlew.bat on a Win10 machine. It fails with the following output:

\grain-theme-new-age-master>gradlew.bat

FAILURE: Build aborted because of an internal error.

* What went wrong:
Build aborted because of an unexpected internal error. Please file an issue at: http://forums.gradle.org.

* Try:
Run with --debug option to get additional debug info.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '10'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:65)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:74)
        at org.gradle.internal.jvm.Jvm.<init>(Jvm.java:84)
        at org.gradle.internal.jvm.Jvm.create(Jvm.java:63)
        at org.gradle.internal.jvm.Jvm.current(Jvm.java:49)
        at org.gradle.launcher.daemon.configuration.CurrentProcess.<init>(CurrentProcess.java:32)
        at org.gradle.launcher.cli.BuildActionsFactory.canUseCurrentProcess(BuildActionsFactory.java:149)
        at org.gradle.launcher.cli.BuildActionsFactory.createAction(BuildActionsFactory.java:129)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.createAction(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:196)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:139)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:46)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.Main.main(Main.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:50)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:32)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:58)

the gradle version, downloaded from gradle wrapper is 1.8, which is also quite ancient (current version is 4.6)... so i tried to execute gradle generate with my installed gradle system (which is 4.6). This create some lengthy reflection error stacktraces in grovy code (which I can past, in case they are of any interest). The same occurs btw if I try to use the clean-blog-theme...

JAVA_HOME points to some Oracle Java 10 JDK.  (java version "10" 2018-03-20), so is my Java version the problem? Or can you give me some hint, what else I should try to fix / change?

Thank you,

with kind regards,

Daniel

**Comment by larixer** [comment]
Hi Daniel

Thanks for reporting this issue. At the moment the last version of Java that Grain supports is Java 8. It is not too hard to make it support Java 9 and higher, but someone needs to work on this, we are busy with other stuff at the moment.

See this issue:
https://github.com/sysgears/grain/issues/27

Can you try Java 8 ?

**Comment by dheldt** [comment]
Hi there,

I will give it a try, but not tonight. According to your fast response I assume, the project is not completly dead, although there seems to be no progress in the last year :) 

I'll keep you posted with Java 8 and 9.

regards,

Daniel

**Comment by larixer** [comment]
@dheldt Cool, thank you!

**Comment by dheldt** [comment]
I tested with Java 8 and gradle generate (with gradle 4.6) does work.

regards,

daniel
